### ISSUE TITLE
Fpt play kodi 1.5.8

### ISSUE THREAD

**Issue by n00b13h** [vinhhrv/cxkodi#3]
Chào Vinh, mình xài fpt play addon v.1.5.8 của bạn trên Kodi 16 Jarvis. Sao nó báo lỗi script failed và mình không coi được đài tv? Giúp mình với nhe. Cám ơn nhiều 😊

**Comment by vinhhrv** [comment]
fpt play dev rảnh đổi hoài :+1:

**Comment by n00b13h** [comment]
Still not working... 😭
